group 'org.pcgy.image_plugin'
version '1.0'

buildscript {
    repositories {
        //google()
       // jcenter()
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google' }
    }

    dependencies {
        classpath 'com.android.tools.build:gradle:7.4.2'
    }
}

rootProject.allprojects {
    repositories {
        //google()
       // jcenter()
        maven { url 'https://maven.aliyun.com/repository/jcenter' }
        maven { url 'https://maven.aliyun.com/repository/google' }
    }
}

apply plugin: 'com.android.library'

android {
    namespace = "org.pcgy.image_plugin"
    compileSdkVersion 33

    defaultConfig {
        minSdkVersion 19
    }
    lintOptions {
        disable 'InvalidPackage'
    }
}
